### ISSUE TITLE
Folder (or content) name shortened with Kirby v4.2

### ISSUE THREAD

**Issue by dimejo** [jonathan-reisdorf/kirby-static-site-generator#1]
The folder name of content is shortened when upgrading from Kirby v4.1 to v4.2.

## Expected Behavior

This is a simplified few of the content and the generated output when using Kirby v4.1:
```
├── assets/
├── content/
│   ├── name_one/
│   ├── another_name/
│   ├── content_three/
│   ├── home/
│   ├── picture.jpg
│   └── site.txt
├── media/
├── site/
├── static/
│   ├── assets/
│   ├── name_one/
│   ├── another_name/
│   ├── content_three/
│   ├── media/
│   ├── favicon.ico
│   └── index.html
├── build.php
├── composer.json
├── composer.lock
└── index.php
```

## Current Behavior

This is the content and output when using Kirby v4.2:
```
├── assets/
├── content/
│   ├── name_one/
│   ├── another_name/
│   ├── content_three/
│   ├── home/
│   ├── picture.jpg
│   └── site.txt
├── media/
├── site/
├── static/
│   ├── assets/
│   ├── name/
│   ├── another/
│   ├── content/
│   ├── media/
│   ├── favicon.ico
│   └── index.html
├── build.php
├── composer.json
├── composer.lock
└── index.php
```
The underscore and everything after it gets removed.

## Context

PHP: 8.2
OS: Windows 10 and Ubuntu (Github Actions)

composer.json:
```
  "require": {
    "php": "~8.1.0 || ~8.2.0 || ~8.3.0",
    "getkirby/cms": "~4.1.0",
    "moritzebeling/kirby-favicon": "^1.0",
    "jreisdorf/kirby-static-site-generator": "^2.0"
  },
  "config": {
    "allow-plugins": {
      "getkirby/composer-installer": true
    },
    "optimize-autoloader": true
  },
```
build.php
```
<?php

require __DIR__ . '/kirby/bootstrap.php';
require __DIR__ . '/site/plugins/static-site-generator/index.php';

$kirby = kirby();
$site = $kirby->site();

$staticSiteGenerator = new JR\StaticSiteGenerator($kirby, $pathsToCopy = [$kirby->roots()->assets(), '.htaccess', 'favicon.ico', 'robots.txt'], $pages = null);
$fileList = $staticSiteGenerator->generate($outputFolder = './static', $baseUrl = '/', $preserve = []);

```

**Comment by jonathan-reisdorf** [comment]
Hello, thanks for reporting this. I think Kirby uses the underscore to differentiate between page order for pagination and the slug. As far as I know, kirby does not support underscores in the URL, at least not when creating the pages through the panel UI. How have you created these pages?

**Comment by jonathan-reisdorf** [comment]
When testing myself, I found this confirmed: The first part before a `_` Kirby parses as page order and everything that follows is the slug. Kirby disallows using the underscore in the panel UI so that there are no bugs when just setting the page to visible without an index.

So, in your example: a structure like this would work as expected:

├── assets/
├── content/
│   ├── 1_name_one/
│   ├── 2_another_name/
│   ├── 3_content_three/
│   ├── home/
│   ├── picture.jpg
│   └── site.txt
├── media/
├── site/
├── static/
│   ├── assets/
│   ├── name_one/
│   ├── another_name/
│   ├── content_three/
│   ├── media/
│   ├── favicon.ico
│   └── index.html
├── build.php
├── composer.json
├── composer.lock
└── index.php
